name: flutter_feign_generator

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  source_gen: ^1.0.0
  built_collection: ^5.0.0
  code_builder: ^3.7.0
  tuple: ^2.0.0
  analyzer: ^1.4.0
  dart_style: ^2.0.0
  build: ^2.0.0
  flutter_feign:
    git:
      url: https://github.com/jalen-mar/flutter_feign.git
      ref: master